# Generated by Django 5.0 on 2023-12-31 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_userprofile_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='user',
        ),
    ]
