# Generated by Django 5.0 on 2024-01-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_provider_provider_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='stripe_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
