# Generated by Django 5.0 on 2024-01-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_provider_business_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
