# Generated by Django 5.0 on 2023-12-31 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_rename_customer_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='provider_logo',
            field=models.ImageField(null=True, upload_to='images/provider-logo'),
        ),
    ]
