# Generated by Django 5.0 on 2024-01-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_services_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='business_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
